services:
  api-gateway:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: api-gateway
    restart: always
    env_file:
      - ../gateway/.env
    volumes:
      - ../gateway:/app
    ports:
      - "8000:8000"
