services:
  api-gateway:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: api-gateway
    restart: always
    env_file:
      - ../gateway/.env
    volumes:
      - ../gateway:/app
    ports:
      - "8000:8000"
    networks:
      - gateway_network
      - service_customer_network
      - service_employee_network
      - service_user_network
      - monitoring_network

  prometheus:
    image: prom/prometheus:v3.4.0-rc.0
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring_network

  grafana:
    image: grafana/grafana:12.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring_network

networks:
  gateway_network:
    driver: bridge
  service_customer_network:
    external: true
  service_employee_network:
    external: true
  service_user_network:
    external: true
  monitoring_network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: